name: Release

on:
  push:
    branches: [master]
    tags: ["v*"]
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Caching docker cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.dockercache
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Setup QEMU
        if: startsWith(github.ref, 'refs/tags/v')
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,i386,s390x,ppc64le
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Extract the Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/yabtt
          tags: |
            type=semver,pattern={{version}}
            type=edge
            type=sha,format=long
            type=sha
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push the Docker container
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: ${{ steps.qemu.outputs.platforms }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=localhost,src=${{ github.workspace }}/.dockercache
          cache-to: type=local,dest=${{ github.workspace }}/.dockercache
