name: Test

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  MIX_ENV: test

jobs:
  build:
    name: Run Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Caching dependencies and compilation results
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-${{ env.MIX_ENV }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 25
          elixir-version: 1.14
      - name: Check the format
        run: mix format --check-formatted
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mix deps.get --only ${MIX_ENV}
          mix deps.compile --force
      - name: Run unit tests
        run: mix test
      - name: Gen coverage report
        run: mix test --cover
